"""add client_applications and verification_sessions tables

Revision ID: af859d3e841a
Revises: ae0ddd06aae8
Create Date: 2026-08-22 13:17:46.844507
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af859d3e841a'
down_revision: Union[str, None] = 'ae0ddd06aae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_level', sa.Enum('api1', 'api2', 'api3', name='apilevel'), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('api_key_prefix', sa.String(length=50), nullable=False),
    sa.Column('server_secret_hash', sa.String(length=64), nullable=False),
    sa.Column('server_secret_prefix', sa.String(length=50), nullable=False),
    sa.Column('allowed_redirect_uris', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('verified_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_applications_api_key_hash'), ['api_key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_applications_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_applications_user_id'), ['user_id'], unique=False)

    op.create_table('verification_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('api_level', sa.Enum('api1', 'api2', 'api3', name='apilevel'), nullable=False),
    sa.Column('redirect_uri', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'IN_PROGRESS', 'VERIFIED', 'FAILED', 'EXPIRED', 'CANCELLED', name='verificationsessionstatus'), nullable=False),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('liveness_session_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('result_retrieved', sa.Boolean(), nullable=False),
    sa.Column('result_retrieved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['client_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_sessions_application_id'), ['application_id'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_sessions_application_id'))

    op.drop_table('verification_sessions')
    with op.batch_alter_table('client_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_client_applications_client_id'))
        batch_op.drop_index(batch_op.f('ix_client_applications_api_key_hash'))

    op.drop_table('client_applications')
    # ### end Alembic commands ###
